id: d35255a5-c67d-44ef-80b2-9d520cd7a709
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: '[POC] MAIN - Tim Feed Configuration'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ecba05e6-ce55-436e-8878-6844beb319fa
    type: start
    task:
      id: ecba05e6-ce55-436e-8878-6844beb319fa
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 30fc1047-2dce-4bf5-89cd-3d7cbd0013a9
    type: playbook
    task:
      id: 30fc1047-2dce-4bf5-89cd-3d7cbd0013a9
      version: -1
      name: '[POC] TIM Feed Configuration'
      playbookName: '[POC] TIM Feed Configuration'
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      Config:
        simple: ${ConfigurationSetup.Lists}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 10
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 255,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
